### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by hdasmith** [vanagnostos/homebridge-drayton-wiser#1]
Sorry for my ignorance, but how do we install your version? I have the other installed that you used as the base, which I installed easily through the homebridge-UI, but I can’t see this version available that way.

**Comment by fjb2020** [comment]
If it helps, I used the command line on my ubuntu homebridge installation - from /usr/lib/node_modules$ sudo npm install -g git+https://github.com/vanagnostos/homebridge-drayton-wiser.git
I'd removed the previous version and config prior to running the above

**Comment by hdasmith** [comment]
Brilliant, thank you.
